ci-cd:
  - changed-files:
      - any-glob-to-any-file: .github/**

dependencies:
  - changed-files:
    - any-glob-to-any-file:
        - pyproject.toml
        - uv.lock

documentation:
  - changed-files:
    - any-glob-to-any-file:
        - docs/**

enhancement:
  - head-branch:
    - ^feature
    - feature
    - ^improve
    - improve

packaging:
  - head-branch:
    - ^packaging
    - packaging
  - changed-files:
    - any-glob-to-any-file:
      - pyproject.toml
      - setup.py

quality:
  - changed-files:
    - any-glob-to-any-file:
      - tests/**/*


tooling:
  - head-branch:
    - ^tooling
    - tooling
  - changed-files:
    - any-glob-to-any-file:
        - .pre-commit-config.yaml
        - justfile
        - pyproject.toml

UI:
  - head-branch:
    - ^ui
    - ui
  - changed-files:
    - any-glob-to-any-file:
        - dip_strike_tools/**/*.ui
        - dip_strike_tools/gui/**
