blank_issues_enabled: true

contact_links:
  - name: Documentation
    url: https://gitlab.com/CNR-IGAG/dip_strike_tools/
    about: Please read carefully the documentation before to submit an issue.
