name: "✅ Linter"

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - .github/workflows/linter.yml
      - pyproject.toml

  pull_request:
    branches:
      - main
    paths:
      - '**.py'
      - .github/workflows/linter.yml
      - pyproject.toml

env:
  PROJECT_FOLDER: "dip_strike_tools"
  PYTHON_VERSION: "3.11"


jobs:
  lint-py:
    name: Python 🐍

    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.5.11"

      - name: Set up Python
        run: uv python install ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          rm -f uv.lock
          uv sync --group dev

      - name: Lint with ruff
        run: |
          # Check for syntax errors and undefined names
          uv run ruff check ${{ env.PROJECT_FOLDER }} --output-format=github
          # Format check
          uv run ruff format ${{ env.PROJECT_FOLDER }} --check

  qt6-check:
    name: PyQt6 6️⃣
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/oslandia/qgis/pyqgis-4-checker/pyqgis-qt-checker:latest
      volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ${{ github.workspace }}:/home/pyqgisdev/
      options: --user root
    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Check PyQt5 to PyQt6 compatibility.
        run: |
          pyqt5_to_pyqt6.py --dry_run ${{ env.PROJECT_FOLDER }}/
          pyqt5_to_pyqt6.py --logfile pyqt6_checker.log ${{ env.PROJECT_FOLDER }}/

      - name: Upload script report if script fails
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: pyqt6-checker-error-report
          path: pyqt6_checker.log
          retention-days: 7
